resources:
  - name: repository
    type: git
    check_every: 24h
    icon: github-circle
    source:
      uri: https://github.com/ONSdigital/takeon-validation-formula-evaluator
      branch: LU-3017-lambda-pipeline
#  - name: base-python-image
#    type: docker-image
#    icon: language-python
#    source:
#      repository: python
#      tag: 3.7-slim
  - name: ecr-image-upload
    type: docker-image
    icon: docker
    source:
      repository: 014669633018.dkr.ecr.eu-west-2.amazonaws.com/take-on-validation-formula-evaluator
      aws_access_key_id: ((concourse-svc-user.api-key))
      aws_secret_access_key: ((concourse-svc-user.api-secret))

jobs:
#  - name: installing-dependencies
#    serial: true
#    plan:
#
#      - get: repository
#        trigger: true
#
#      - get: base-python-image
#        params:
#          save: true
#
#      - put: ecr-image-upload
#        params:
#          load_base: base-python-image
#          build: repository

  - name: linting-&-tests
    serial: true
    plan:
      - get: repository
        trigger: true
#        passed: [installing-dependencies]
#        version: every

#      - get: base-python-image
#        params:
#          save: true

      - put: ecr-image-upload
        params:
#          load_base: base-python-image
          build: repository

      - task: aws-tests
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: 014669633018.dkr.ecr.eu-west-2.amazonaws.com/take-on-validation-formula-evaluator
              aws_access_key_id: ((concourse-svc-user.api-key))
              aws_secret_access_key: ((concourse-svc-user.api-secret))
          inputs:
            - name: repository
          run:
            path: sh
            args:
              - -exc
              - |
                cd repository
                PYTHONPATH=$(pwd)/repository python test_harness.py
        on_failure:
          put: repository
          params:
            path: repository
            status: failure
            description: Failing tests are present

  - name: serverless-deploy
    plan:
      - get: repository
        trigger: true
      - task: serverless-aws
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: 014669633018.dkr.ecr.eu-west-2.amazonaws.com/take-on-validation-formula-evaluator
              aws_access_key_id: ((concourse-svc-user.api-key))
              aws_secret_access_key: ((concourse-svc-user.api-secret))
          params:
            AWS_ACCESS_KEY_ID: ((concourse-svc-user.api-key))
            AWS_SECRET_ACCESS_KEY: ((concourse-svc-user.api-secret))
            SLS_DEBUG: 1
          inputs:
            - name: repository
          run:
            path: repository/serverless.sh